services:
  foodfetchers-site:
    restart: unless-stopped
    build: site
    # set this port to whatever you want the site open on.
    # you do NOT need to expose ports like this for foodfetchers-database.
    #ports: 
    #  - '8080:80'
    volumes:
      # TODO: for some reason, this mount does not have write permission set
      # and chmod needs to be run to make it writeable
      - "coverImages:/var/www/html/coverimages:rw" 
      - "./site/html/:/var/www/html/"
      - "./site/config/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro"
      - "./site/config/php.ini:/usr/local/etc/php/php.ini:ro"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - foodfetchers-database
    develop:
      #watch:
      #  - action: sync
      #    path: ./site/html
      #    target: /var/www/html
      #    ignore:
      #      - coverimages
  
  foodfetchers-database:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
#    ports:
#      - '5432'
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./database/resetTables.sh:/docker-entrypoint-initdb.d/resetTables.sh:ro"

volumes:
  coverImages:
  db: